# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:  #手动运行workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
    
      - name: Generate Snake
        uses: Platane/snk@v2.2.1 #在marketspace中generate-snake-game-from-github-contribution-grid
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile-snake-contrib/github-contribution-grid-snake.svg
            profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark

    
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9 #在marketplace中的add&commit
        with:
          message: ':rocket: Update by Snake'
